### ISSUE TITLE
Zotero Groups export local file?

### ISSUE THREAD

**Issue by rkrug** [oeysan/c2z#1]
Hi

This package looks great for accessing Zotero.

But I am looking for a way to access Group libraries for essentially downloading them in a format, which I can use in further analysis - is this possible? I couldn't figure it out yet.

Thanks,

Rainer

**Comment by oeysan** [comment]
Hi,

Sorry for the late reply, I've been on vacation.

It is possible to access group libraries and export them according to the [Zotero Web API Documentation](https://www.zotero.org/support/dev/web_api/v3/basics#export_formats).

`example <- Zotero(
  user = FALSE,
  id = "4986462",
  api = NA,
  library = TRUE,
  export = TRUE,
  format = "json"
)
example$results`

I hope this helps!

**Comment by rkrug** [comment]
Thanks a lot - yes this helps.
